Blasting 
========


### Convert SNP.SNPs consensus seqs to FASTA format 

The consensus sequences of the SNP.SNPs matrix produced by the `1.PopSamples_PostCleaning.r` can be exported to Fasta with the script:

```
cd ~/../../Volumes/TO_GO_1/BerL_1_2_3/3Berberis_phylogeo
R CMD BATCH /bin/Berberisphylogeo_generatefasta.r
```

### Run blasting job

Blast+ is a module by NCBI that takes a given DNA sequence and looks to which other DNA sequence in a given database it is more similar to. We run this locally, as blast+ allows this if NCBI databases are downloaded. This is faster and allows to parse the output more easily. See the manual at http://www.ncbi.nlm.nih.gov/books/NBK1763/#_CmdLineAppsManual_Quick_start_ for details.


The script update_blastdb.pl that comes with blast+ can be used to download the desired databases already formatted for blast. We downloaded "nt" (nucleotide) and "taxdb" (taxonomy). Notice that the BLAST taxonomy database is required in order to print the scientific name, common name, blast name etc as part of the BLAST report. 

The -entrez_query flag is only available if using blast+ remotely, so to be able to restric the query to green plants in the nt database we used the -gilist option with the file `/docs/greenplants.gi.txt`. This file was created by searching on the webiterface (http://www.ncbi.nlm.nih.gov/nuccore/) of the Nucleotide database with: `viridiplantae[organism] NOT wgs[filter] NOT htg[div] NOT pat[div] NOT sts[div]` and saving the output as GI LIST.




Our blasting job looks like:


```
#!/bin/sh
#BSUB -q long
#BSUB -J blast_test
#BSUB -B 
#BSUB -N 
#BSUB -oo blast_test.out
#BSUB -eo blast_test.out
. /etc/profile


module add blast/ncbi-2.2.29+

## Filter low complexity regions using dustmasker
# Create masking information using dustmasker
dustmasker -in PopSamples_BeralpBt_short_test.FASTA -infmt fasta -parse_seqids \
-outfmt maskinfo_asn1_bin -out PopSamples_BeralpBt_short_test_dust.asnb

# Create BLAST database with the masking information
makeblastdb -in PopSamples_BeralpBt_short_test.FASTA -input_type fasta -dbtype nucl -parse_seqids \
 -mask_data PopSamples_BeralpBt_short_test_dust.asnb -out PopSamples_BeralpBt_short_test -title \
 "PopSamples_BeralpBt_short_testdusted"


## Run blast

# tell blast where to look for databases 
export BLASTDB=/gpfs/data/datasets/blastdb/:/gpfs/data/datasets/blastdb/nt/:/gpfs/bio/bxh10nyu/blast_test/:/gpfs/data/datasets/blastdb/taxdb

# blast
blastn -db nt -query PopSamples_BeralpBt_short_test.FASTA  -word_size 11 -evalue 10 -gapopen 5 -gapextend 2 -best_hit_overhang 0.1 -best_hit_score_edge 0.1 -max_target_seqs 1 -out blast_test.out -outfmt "7 qacc evalue score qcovs pident length staxids sscinames stitle"


# Blastes data against green plant nucleotide database 
# word_size Length of initial exact match.
# gapopen Cost to open a gap.
# gapoextend Cost to extend a gap 


### Write it as tabular format with comments (7), 
# qacc means Query accesion
# evalue means Expect value
# bitscore means Bit score (normalized raw score that considers the search space)
# qcovs means Query Coverage Per Subject
# length means Alignment length
# pident means Percentage of identical matches
# staxids means unique Subject Taxonomy ID(s), separated by a ';'(in numerical order)
# sscinames means unique Subject Scientific Name(s), separated by a ';'
# stitle means Subject Title


```

-entrez_query viridiplantae[organism]

```
bsub > 
```

pfs/data/datasets/blastdb:







stitle means Subject Title

qcovs means Query Coverage Per Subject

pident means Percentage of identical matches

staxids means unique Subject Taxonomy ID(s)

sscinames means unique Subject Scientific Name(s)
 

remote search? 


max_target_seqs



blastn -db nt -remote -query PopSamples_BeralpBt_short_test.FASTA -out blast_test.outnt